---
title: "Predictive Maintenance"
author: "Reza Dwi Utomo"
date: "3/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

The trend of Industry 4.0 spreads drastically. Data abundance and rapid ICT (Information and Communication Technology), especially AI (Artificial Intelligence), development become a key factor to such next generation industry. Many industrial stakeholders compete to implement it. IoT (Internet of Things) and Big Data are some of its implementation.

**Industri mana saja yang menggunakan pred maint dan tulis problem**

In industrial sector, one of the applications of Industry 4.0 can be found in so-called Predictive Maintenance. This brand-new type of maintenance benefits from IoT and Big Data to perform maintenance. It completely differs from its predecessors, i.e. corrective and preventive maintenances. Both traditional techniques emphasize human-based and manual investigation on machine conditions. Eventhough they are still important in some aspects, industry players are not recommended to leave their product maintenance alone with both techniques. For example, you could perform run-to-failure for your uncritical equipment; you might not need this predictive maintenance method. Even the uncritical equipment simply does not need preventive maintenance. However, you could not think the same for your critical equipment where any failure is totally untolerated for any condition. The old-school preventive maintenance might suggest you to create a maintenance schedule in order to carry out maintenance periodically. It was expected you could perform maintentance in correct moments to minimize any undesired failure. Nevertheless, what actually happened were, for example, more cost upfront, over maintenance, labor intensive, unpredictability, and many more. On the other hand, Predictive Maintenance comes to offer a new approach to overcome those drawbacks. Based on the advantages of IoT and Big Data technology, some of predictive maintenance applications are remaining useful life (RUL) prediction, failure classification, and image-based defect detection.

The RUL prediction lets you to predict what time cycle left before the equipment going to fail. This, consequently, will maximize your equipment performance until its real capacity before failure where in turn your cost also will be minimized. Subsequently, failure classification provides you the easiness to categorize the failure modes based on their characteristics. This will aid you to provide different maintenance treatments for dissimilar failure modes. Therefore, it is unnecessary to allocate profuse man powers, tools, and treatments for each failure mode. Afterwards, for image-based defect detection, you could easily detect any defect on your products. This will significantly reduce the operator's human-error when he ran the manual visual inspection. By applying this technique, even you could execute quality control inspection autonomously, quickly, and plentifully. This will help you to identify the suppliers with frequent defect supply. Thus, once again, you could maximize outputs while minimizing cost.

*tulis singkat metode yang digunakannya dan kaitannya dengan variabel yang tersedia*

In this article, the aforementioned three applications of predictive maintenance are going to be discussed. As case studies and due to the lack of datasets, unsimilar datasets are going to be used for each application. The datasets are the following:

1. dataset candidates: [NASA Turbofan Engine](https://ti.arc.nasa.gov/tech/dash/groups/pcoe/prognostic-data-repository/#turbofan), [IEEE PHM 2012 Data Challenge Dataset](https://github.com/Lucky-Loek/ieee-phm-2012-data-challenge-dataset), or [Scania dataset](https://www.kaggle.com/uciml/aps-failure-at-scania-trucks-data-set) > for Remaining Useful Life (Regression)

2. dataset candidates: [Amruthnath dataset](https://github.com/nagdevAmruthnath/Predictive-Maintenance) or [Faulty Steel Plates UCI dataset](https://www.kaggle.com/uciml/faulty-steel-plates) > for failure classification (Unsupervised Learning)

3. Steel Defect Detection dataset (acquired from [Kaggle](https://www.kaggle.com/c/severstal-steel-defect-detection/overview)) is used for image-recognition based defect detection

The methods used for each application are regression, unsupervised learning, and image classification, respectively.